### ISSUE TITLE
Is a port of "Word autocompleter" on 2.1 planned ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [phu54321/anki_plugins#11]
Thanks :)

**Comment by phu54321** [comment]
Sorry for the late reply :(

No, I don't plan to do that. It seems like not a lot of people is using it, and especially I'm not using it well. Sorry

**Comment by thiswillbeyourgithub** [comment]
Oh that's too bad, I'm sure lots of computer science and med students would love this. Do you have any idea if the porting is going to be hard or if it's just a one line change ?

**Comment by phu54321** [comment]
certainly not an one line change. not brilliantly lot of changes, but still a lot of stuff

**Comment by thiswillbeyourgithub** [comment]
What do you think of uploading an "alpha" quick and dirty change to ankiweb? This way if someone with the time and the interested sees it mentionned in the official anki 2.1 addon list he or she might try to port it.

I just think it's too bad if your addon isn't mentionned anywhere and nobody knows that someone (you) already did most of the work. As time goes on nobody is going to look at the anki 2.0 addon list...
