### ISSUE TITLE
Time away from deck counts towards cards 

### ISSUE THREAD

**Issue by Sue9112** [phu54321/anki_plugins#12]
Great add-on, but whenever I exit the deck it still counts the time spent away from the deck as how long it took to complete a card- which throws of the time estimation. Is there a way to only count the time spent seeing cards, and not just from when you first open the deck to when you complete it?

**Comment by phu54321** [comment]
will fix till 03/12

Related to #19

**Comment by clubmeh** [comment]
Personally, I found this was one of the BEST features of this addon. Really showed you how productive you were being (and how much time was being wasted). Is there anyway I can replicate this effect in the newest version?
