### ISSUE TITLE
Doesn't seem to work with subdecks

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [phu54321/anki_plugins#13]
Hi,

I think this addon doesn't count the new cards in every subdecks but I think it should. What do you think ?

Thanks for reading !

**Comment by phu54321** [comment]
Why is this an issue? If you're reviewing from a parent deck, not all of the new cards of subdeck would be considered for a learning session. I think I don't fully understand what you really mean. Could you elaborate more?
