### ISSUE TITLE
Toggle to Bottom

### ISSUE THREAD

**Issue by 2pascal** [phu54321/anki_plugins#15]
Is there a way to move this bar to the bottom? I was comparing your code with the Glutanimate source for ideas but couldn't find any way to move it. Thank you.

**Comment by phu54321** [comment]
While moving a deck to the bottom is easy, I'll have to look for how anki manages addon's config. I'm not really into creating GUI configuration window, so you'd have to manually edit JSON thingies to apply such settings.

Will fix at 2020-03-18
