### ISSUE TITLE
Elapsed time resets erroneously and remaining time breaks

### ISSUE THREAD

**Issue by StookDog** [phu54321/anki_plugins#19]
The time has been resetting very frequently when I reschedule cards using the Rememorize addon, the "undo" hotkey, or when switching into fullscreen. E.g. I'll be 45 minutes into a review and will press undo and it'll say I'm 0.0 minutes in. Thanks!

Edit: on looking into this further, I was messing around with the code to see if I could find out what the issue was and upon changing this line: 
"if abs(currentRemainingReviews - lastRemainingReviews) >= 20:"     *TO THIS* -->
"if abs(currentRemainingReviews - lastRemainingReviews) >= 2000:"

When I clicked "undo" the time didn't reset to "0.0" but rather to a different number and the estimator then broke (estimated very short times). I think it must be something about clicking undo that messes up the remainingreviews. Just thought I'd throw that in there, not sure if it helps.

Also, I noticed the rescheduling of cards tends to mess up the Remaining time estimation while undo messes up the elapsed time more frequently, although I've seen them both affect both.

**Comment by phu54321** [comment]
will fix till 03/12

**Comment by phu54321** [comment]
I think that when such massive reschedule occurs It'd be better to just reset the estimator and everything. How do you think?

**Comment by StookDog** [comment]
Yeah that would probably be good, just to start it as a new session if the break is longer than x minutes or something. Another option, if possible, may be to just ignore answer times longer than x minutes/seconds and keep the previous data. If it were configurable it could be tested a few different ways.
