### ISSUE TITLE
would I make a suggestion? for the pastehtml plugin

### ISSUE THREAD

**Issue by breezeit** [phu54321/anki_plugins#2]
Thanks for you and your plugins！They are useful!
would I make a suggestion?
In the most time，only need the pure text for a uniform format.other time need html-past.If there are two pastes will be better.
html-paste  with one shortcut(such as shift+ctrl+v?), and the pure-paste(only the text) with normal ctrl+v.
thanks  again!

**Comment by phu54321** [comment]
I like that idea. Will implement that in a near future
