### ISSUE TITLE
New update relies on what button is pressed rather than the card state

### ISSUE THREAD

**Issue by zer0xs** [phu54321/anki_plugins#21]
In the new update, the addon now looks at what button is pressed rather than the actual card state. This breaks the plugin because 1. If you undo after rating a card, the plugin doesn't catch it. 2. If on the question side, hitting '1' '2' or '3' without flipping the card over will make the addon think you rated a card when you didn't. This messes with the addon math as well since the number due doesn't change.

**Comment by phu54321** [comment]
Split into two issues. Follow at #22 and #23
