### ISSUE TITLE
"Bar should not be transparant" not fixed correctly

### ISSUE THREAD

**Issue by zer0xs** [phu54321/anki_plugins#25]
On line 107 of RemainingTime.py, you added this
`<path d="M0 0 h1 V1 h-1 Z" fill="white" />`

However, this change assumes a white background and not in night mode (which changes font color to white). Please revert.

**Comment by phu54321** [comment]
Do you know any other addon that changes the background color? Ultimately I'd like to have
background of the bar addon follows that of Anki.

-- Added
I've published a hotfix for the issue. Text in the progress bar will now be black.

**Comment by zer0xs** [comment]
So, that works temporarily, however, I think the way you had it before works better. Anki's built-in nightmode changes the background color. The default white background is very harsh.

**Comment by phu54321** [comment]
Addon before the change had a problem that the content of the card overlaps with the progress bar text, which is unacceptable to me.

**Comment by phu54321** [comment]
Maybe it would be worthwhile to just add a option of dark background progress bar.

**Comment by phu54321** [comment]
> Maybe it would be worthwhile to just add a option of dark background progress bar.

Will implement this scheme on 03/28.

**Comment by kanjieater** [comment]
![image](https://user-images.githubusercontent.com/32607317/77856506-4b0b2280-71bd-11ea-8649-06f9fd0e69f1.png)
This has made my issue of it covering up content worse. The colors will invert if I set it to dark mode at least.
