### ISSUE TITLE
Ctrl+number returns undefined output

### ISSUE THREAD

**Issue by tjbrn** [phu54321/anki_plugins#3]
Autocompleting with "tab" key works normaly, but when using the combination "Ctrl+number", the output returned is "undefined"

![image](https://user-images.githubusercontent.com/10359351/40887692-a462ceac-6722-11e8-83fa-25a89da0a09f.png)

Tested under clean profile
Anki 2.0.50
Qt 4.8.1
PyQt 4.9.1

**Comment by phu54321** [comment]
Will check out when I port word autocomplete addon to Anki 2.1
