### ISSUE TITLE
Basic to Cloze add-on changed all my basic cards to error cards. Please help.

### ISSUE THREAD

**Issue by generalissimo3** [phu54321/anki_plugins#4]
I added this add on to my deck and it ended up not working. So I removed it. After removing it I had issues with every single basic card in ALL of my decks. They now show error messages every-time I try and view them. It will say "The front of this card is empty. Please run Tools>Empty Cards." then when I click on "edit" on the card it brings me to the edit page the card looks perfectly fine. I have included images. Also, when I follow the directions and click on Tools>Empty Cards it pops up almost 100 cards that it says I need to delete that were screwed up by the add on. Any help would be greatly appreciated! otherwise I have to go back and copy and paste each card to a new card and delete the old one. Thank you!

![image](https://user-images.githubusercontent.com/42456007/44243272-26a33380-a19c-11e8-98c6-5e1987a5ecaa.png)

![image](https://user-images.githubusercontent.com/42456007/44243260-1a1edb00-a19c-11e8-92d8-4c8560dbf76c.png)

**Comment by generalissimo3** [comment]
When I click on the card it pops up with cloze settings when I made this card as a basic card a week or two before downloading this add on!

![image](https://user-images.githubusercontent.com/42456007/44243428-06c03f80-a19d-11e8-911a-e544707d462f.png)

**Comment by phu54321** [comment]
I'm so sorry about that. Would you mind sending your apkg file to phu54321@naver.com? Or contact me on discord via trgk#3180. I think i can give you a help.

**Comment by generalissimo3** [comment]
I can't seem to find that username on Discord. But, it seems to have happened across all 5 of my decks. Thanks for your help!
- I emailed you. Let me know if you need anything else. Thank you.

**Comment by phu54321** [comment]
I've seen the decks.

![image](https://user-images.githubusercontent.com/775265/44245704-09f71200-a215-11e8-8be3-e8e65422aec7.png)

Would you mind changing the front template to `{{Front}}`?
I'll investigate more about this issue later.

**Comment by generalissimo3** [comment]
Okay awesome I will go through and do that. That's a lot easier fix then replacing the cards. thanks for your help!

**Comment by phu54321** [comment]
Is the issue resolved? If then please close the issue :)
